// Model parameters and dataset statistics generated by train_model.py using Scikit-Learn
const SCIKIT_LEARN_MODEL_DATA = {
  "lr_model": {
    "intercept": -1.6519628028216642,
    "coefficients": {
      "Tenure": -0.056645787382404535,
      "MonthlyCharges": 0.01141121984030625,
      "SupportTickets": 0.5566221973820463,
      "SeniorCitizen": 0.4518369304076574,
      "Partner_Yes": -0.09261977859965397,
      "Contract_MonthToMonth": 1.3190326882660948,
      "Contract_TwoYear": -1.2177883205304456,
      "Internet_FiberOptic": 0.10336667605621788,
      "TechSupport_No": 0.6002438617715784,
      "Payment_ElectronicCheck": 0.564568502641927,
      "PaperlessBilling_Yes": -0.0323774778940193
    },
    "metrics": {
      "accuracy": 0.785,
      "precision": 0.7188,
      "recall": 0.6479,
      "auc": 0.842
    }
  },
  "dt_model": {
    "decision_tree": {
      "type": "node",
      "feature": "Contract_MonthToMonth",
      "threshold": 0.5,
      "left": {
        "type": "node",
        "feature": "Tenure",
        "threshold": 22.5,
        "left": {
          "type": "node",
          "feature": "SupportTickets",
          "threshold": 1.5,
          "left": {
            "type": "node",
            "feature": "Partner_Yes",
            "threshold": 0.5,
            "left": {
              "type": "leaf",
              "probability": 0.1569,
              "samples": 1
            },
            "right": {
              "type": "leaf",
              "probability": 0.3333,
              "samples": 1
            }
          },
          "right": {
            "type": "node",
            "feature": "Tenure",
            "threshold": 17.5,
            "left": {
              "type": "leaf",
              "probability": 0.3846,
              "samples": 1
            },
            "right": {
              "type": "leaf",
              "probability": 1.0,
              "samples": 1
            }
          }
        },
        "right": {
          "type": "node",
          "feature": "MonthlyCharges",
          "threshold": 74.01,
          "left": {
            "type": "node",
            "feature": "Tenure",
            "threshold": 25.5,
            "left": {
              "type": "leaf",
              "probability": 0.2857,
              "samples": 1
            },
            "right": {
              "type": "leaf",
              "probability": 0.0236,
              "samples": 1
            }
          },
          "right": {
            "type": "node",
            "feature": "Contract_TwoYear",
            "threshold": 0.5,
            "left": {
              "type": "leaf",
              "probability": 0.2407,
              "samples": 1
            },
            "right": {
              "type": "leaf",
              "probability": 0.0794,
              "samples": 1
            }
          }
        }
      },
      "right": {
        "type": "node",
        "feature": "Tenure",
        "threshold": 31.5,
        "left": {
          "type": "node",
          "feature": "SupportTickets",
          "threshold": 1.5,
          "left": {
            "type": "node",
            "feature": "Payment_ElectronicCheck",
            "threshold": 0.5,
            "left": {
              "type": "leaf",
              "probability": 0.5778,
              "samples": 1
            },
            "right": {
              "type": "leaf",
              "probability": 0.8421,
              "samples": 1
            }
          },
          "right": {
            "type": "node",
            "feature": "TechSupport_No",
            "threshold": 0.5,
            "left": {
              "type": "leaf",
              "probability": 0.7826,
              "samples": 1
            },
            "right": {
              "type": "leaf",
              "probability": 0.9277,
              "samples": 1
            }
          }
        },
        "right": {
          "type": "node",
          "feature": "SupportTickets",
          "threshold": 1.5,
          "left": {
            "type": "node",
            "feature": "MonthlyCharges",
            "threshold": 90.835,
            "left": {
              "type": "leaf",
              "probability": 0.1023,
              "samples": 1
            },
            "right": {
              "type": "leaf",
              "probability": 0.3158,
              "samples": 1
            }
          },
          "right": {
            "type": "node",
            "feature": "Tenure",
            "threshold": 45.5,
            "left": {
              "type": "leaf",
              "probability": 0.6809,
              "samples": 1
            },
            "right": {
              "type": "leaf",
              "probability": 0.3563,
              "samples": 1
            }
          }
        }
      }
    },
    "importances": {
      "Tenure": 0.43894303511054766,
      "MonthlyCharges": 0.026621355416899726,
      "SupportTickets": 0.1261617875456868,
      "SeniorCitizen": 0.0,
      "Partner_Yes": 0.007608566829138668,
      "Contract_MonthToMonth": 0.36734741735524745,
      "Contract_TwoYear": 0.009794365321750566,
      "Internet_FiberOptic": 0.0,
      "TechSupport_No": 0.004904554054755869,
      "Payment_ElectronicCheck": 0.018618918365973267,
      "PaperlessBilling_Yes": 0.0
    },
    "metrics": {
      "accuracy": 0.775,
      "precision": 0.7097,
      "recall": 0.6197,
      "auc": 0.8135
    }
  },
  "averages": {
    "tenure": 36.67,
    "monthly_charges": 68.97,
    "support_tickets": 1.44,
    "total_samples": 1000,
    "churn_rate": 0.36
  },
  "segments": {
    "churn_by_contract": {
      "Month-to-month": 0.5187,
      "One year": 0.2273,
      "Two year": 0.0962
    },
    "churn_by_tech_support": {
      "No": 0.4087,
      "Yes": 0.273
    },
    "churn_by_internet": {
      "DSL": 0.287,
      "Fiber optic": 0.3943,
      "No": 0.3968
    },
    "charges_by_churn": {
      "0": 68.09,
      "1": 70.54
    }
  }
};

// Expose data if running in Node.js environment for testing, otherwise it is global in browser
if (typeof module !== 'undefined' && module.exports) {
    module.exports = SCIKIT_LEARN_MODEL_DATA;
}
